// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413064816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zhangsan@example.com",
                            Name = "张三",
                            PasswordHash = "AQAAAAIAAYagAAAAEC4r86NsucOCTWksT+P35f6arjPS8EqXSNXrjLYS/Hjc4QEG79+VG94Ymi0E3iJofw=="
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lisi@example.com",
                            Name = "李四",
                            PasswordHash = "AQAAAAIAAYagAAAAEC4r86NsucOCTWksT+P35f6arjPS8EqXSNXrjLYS/Hjc4QEG79+VG94Ymi0E3iJofw=="
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "wangwu@example.com",
                            Name = "王五",
                            PasswordHash = "AQAAAAIAAYagAAAAEC4r86NsucOCTWksT+P35f6arjPS8EqXSNXrjLYS/Hjc4QEG79+VG94Ymi0E3iJofw=="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
